# Basic
title: whisper
subtitle: Hello,my name is whisper and this is my homePage
welcome_message: 黎戈
description: 不管见识高低，一个人深度整理和收拾自己的内心，这事本身就很迷人。
creator: <a href="https://github.com/whisper12">@whisper</a>

url: "https://github.com/whisper12"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: grey

# The blog button should not be removed.
blog_button:
    title: 首页
    description: Visit index

# Navigation buttons in the front page.
nav:
    # - {title: 首页, description: index, url: '/'}
    - {title: 博客, description: My blog, url: '/#blog', blog: true,}
    - {title: 项目, description: My Projects, url: ''}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
plugins: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    # disqus: 
    # duoshuo: 
    
# Social
social:
    # weibo: onevcat
    github: whisper12
    # twitter: onevcat
    # gplus: 107108267983477358170
    mail: 542634964@qq.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
